apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-v2
  labels:
    app: provider-v2
    version: v2
spec:
  replicas: 1
  template:
    metadata:
      name: provider
      labels:
        app: provider
        version: v2
    spec:
      containers:
        - name: provider-v2
          image: provider:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
      restartPolicy: Always
  selector:
    matchLabels:
      app: provider
      version: v2